### ISSUE TITLE
Header field show on Activity Table, but not be visible as a Header field.

### ISSUE THREAD

**Issue by keld1280** [CRITFC/Helpdesk#10]
Would love to be able to have fields show up in the Activity Table, but not have to be visible in other windows.  For example, we have a field that is auto generated in the Header (CreateDate - date the activity was created) which is does not need to be visible in the Header, but is needed in the Activity Table so that the activities can be sorted and found easily for QA/QC process.

**Comment by nowinski** [comment]
Setting the dataset level field control type to HIDDEN addresses this need.
