### ISSUE TITLE
Frontend decimals truncated

### ISSUE THREAD

**Issue by nowinski** [CRITFC/Helpdesk#12]
CDMS frontend appears to save decimal precision to the database correctly when trailing zeros are entered into the data entry screen but trailing zeros are truncated when decimal values are retrieved for display on the data edit/view pages. 

***This issue has been referred to CTUIR***

**Comment by cwatry** [comment]
We have noticed this as well as it affects our Lat/Long data precision which uses a decimal data type.

**Comment by nowinski** [comment]
CTUIR will handle this one
