### ISSUE TITLE
Button to push data to CAX missing (bug?)

### ISSUE THREAD

**Issue by cwatry** [CRITFC/Helpdesk#13]
Just as title states.  Applies to StreamNet tables designed for CAX data.  Also, for new StreamNet tables designed for CAX data, how do we create the link to the CAX api for those datasets??

**Comment by nowinski** [comment]
Confirmed. The button used to appear on the project landing page in CDMS 1.0. The html was pulled from aap\core\projects\components\project-detail\project-datasets.html but this file doesn't appear to exist in CDMS 2.0. 

I propose adding the button back to the project landing page next to the Edit Project button and restricting access to Admins.

![Capture](https://user-images.githubusercontent.com/8331885/69365981-400e1780-0c4a-11ea-83cb-0de0079f040e.PNG)

The html would go in project-landing.html

![Capture](https://user-images.githubusercontent.com/8331885/69365878-105f0f80-0c4a-11ea-899b-1b9325c942a3.PNG)

**Comment by nowinski** [comment]
Ah--I almost forgot to mention that after adding the html the button will only appear if the project is named "StreamNet" which make sense but also kinda feels like this . . .

![pix](https://user-images.githubusercontent.com/8331885/69366641-9def2f00-0c4b-11ea-9f9d-6b6e88f3ad3c.jpg)

**Comment by kenburcham** [comment]
Yeah, that's not exactly following The Principle of Least Surprise, is it?!  

A little bit of an improvement would be to have the button only show if the project has a StreamNet  dataset (has one of the 3 StreamNet datastoreids). 

It would also be nice to have an connector options page where you could provide parameters for the script such as which dataset(s) you want to sync. And also it'd be super useful to be able to see run history and results. 

Maybe what we're talking about here is a "external API connector" feature that thinks about this StreamNet but also other use cases we might want to connect up CDMS... Fins, PITAGIS, etc., etc.

**Comment by nowinski** [comment]
Push this to tribal CDMS
