### ISSUE TITLE
QA field not displayed in front end (bug?)

### ISSUE THREAD

**Issue by cwatry** [CRITFC/Helpdesk#16]
The QA field is not present/displayed in the detail of a number of recently created datasets.  The back-end SQL _Detail table seems to include all the appropriate fields, including: RowId, RowStatusId, and QAStatusId.  However, the front-end Admin UI does not have this field listed in either the Master Dataset grid or the Project dataset grid as it is in older datasets.  This only seems to affect datasets created since we implemented v2.0 although I'm not sure that's the root cause.

**Comment by nowinski** [comment]
All of these fields belong to the Activity System Fields datastore, which is new in CDMS 2.0. Check your config.js file and make sure DATASTORE_ACTIVITYSYSTEMFIELDS (around line 77) equals the datastoreId for your ActivitySytemsFields datastore.

**Comment by kenburcham** [comment]
Also, new datasets need to have the system fields you want to use added into the datasetfields. The reason we changed this is because in CDMS 1.0, these "magic fields" couldn't be controlled. By making them explicit, you can add them or not, as necessary.

In my dataset create script I usually have something like this where 23 is the Id of my ActivitySystemFields datastore:

```

-- Add in the activity system fields
INSERT INTO dbo.DatasetFields(DatasetId, FieldId, FieldRoleId, CreateDateTime, Label, DbColumnName, Validation, SourceId, InstrumentId, OrderIndex, ControlType, [Rule])
SELECT
    DatasetId       = @datasetid,
    FieldId        = f.Id,
    FieldRoleId    = f.FieldRoleId,
    CreateDateTime = GETDATE(),
    Label          = f.Name,
    DbColumnName   = f.DbColumnName,
    Validation     = f.Validation,
    SourceId       = 1,
    InstrumentId   = NULL,
    OrderIndex     = 1, 
    ControlType    = f.ControlType,
    [Rule]         = f.[Rule]
FROM Fields as f WHERE DatastoreId = 23 AND DbColumnName in ('QAStatus','QAComments','LocationId','QAStatusId');
```
