### ISSUE TITLE
Example text for number fields in query tool

### ISSUE THREAD

**Issue by cwatry** [CRITFC/Helpdesk#19]
When trying to establish criteria in the query tool for number values in the Numeric Expression textbox, the example displays '= 42' as the proper syntax to use when querying for the value '42'; however, '=42' does not allow the query to execute and should instead be entered only as '42'.  As such, the text in the examples needs to be changed to reflect this nuance for building functional numeric expressions when searching for exact values.  The syntax for all other examples appears correct as expressions written in the provided format allow the query to execute properly.  Should be an easy fix, but important to avoid confusion for general users.

**Comment by nowinski** [comment]
Traced this to services/Resourced/QueryHelper.cs.  The query condition operator is set to "=" at line 185. If user enters the value "=1" into the expression field, the result is condition + value, or ==1. 

![Capture](https://user-images.githubusercontent.com/8331885/73298297-e8e47000-41c1-11ea-8c39-99e094692265.PNG)

So, how about we handle "=1" the same way CDMS handles > and < . . . just set condition to ""

![Capture](https://user-images.githubusercontent.com/8331885/73298513-4aa4da00-41c2-11ea-9228-c06b15fed255.PNG)

This way the query runs if user enters =1 or 1

**Comment by nowinski** [comment]
Push to tribal CDMS
