### ISSUE TITLE
Bug: Time fields return Invalid Date error

### ISSUE THREAD

**Issue by cwatry** [CRITFC/Helpdesk#2]
We have at least two datasets w/ time-only fields where both data type and control type = "time".  The time values display properly when viewing a record from the Activities page or when displayed in the query tool grid; however, on the Data Entry page and in all files exported using the query tool the time does not display and instead "Invalid Date" is displayed in the time fields.

**Comment by nowinski** [comment]
What is the SQL Server data type?

**Comment by cwatry** [comment]
The SQL data type is set to ‘datetime’ for those fields.

**Comment by nowinski** [comment]
Please try switching the data type to string in CDMS>Admin>Datasets>Edit Master Dataset and let me know if that resolves the Invalid Date issue. This may not be the best solution but it did resolve the Invalid Date bug on the View Activity page.

**Comment by cwatry** [comment]
That doesn’t seem to have worked

**Comment by nowinski** [comment]
I was able to reproduce the Invalid Date message in the Activities grid and export files but only when the time value is NULL in SQL Server. When you're back in the office, I'd like to get a fresh backup of your database and an ActivityID for records with time values that display as Invalid Date. That would give me a much better sense of exactly what's happening. Also, how the data were imported? CDMS 1.0 importer, CDMS 2.0 importer, or manually with SQL scripts?

![Capture](https://user-images.githubusercontent.com/8331885/59934856-5b59ca00-9401-11e9-921a-465e899aebae.PNG)

![Capture](https://user-images.githubusercontent.com/8331885/59935625-0ae36c00-9403-11e9-8522-d9469292fe7a.PNG)

**Comment by nowinski** [comment]
Think I've finally traced this to its root. You most likely have NULL datetime values in your database resulting from a) the way Excel stores and formats datetime values and b) the way CDMS handles datetimes prior to 1/1/1901. Please check your database and confirm. We can resolve by concatenating date & time in Excel or by making some fairly simple CDMS edits. Give me a call to discuss.

**Comment by cwatry** [comment]
Aha!!!  So, we don’t have any NULL values in any time fields as we set defaults to 00:00 if no time was provided in the original data.  However, I noticed that the generic date portion of this field in SQL has the prefix date of 1/1/1900 not 1901.  I know this is a problem as I ran into this issue when trying to format data in Excel for importing into CDMS (for whatever reason, Excel defaults to 1900 instead of 1901 ofr the date-time format).  Based on that experience and your discovery, I should be able to easily REPLACE ‘1900’ w/ ‘1901’ for the year portion of the date-time value so the Time values display properly, right?  Let me give this a try in my Local_DEV to see if I can make it work, and I will call if I need assistance.  Thanks for all the sleuthing to figure out the issue, I’ve been so busy this week I forgot all about it.  I’ll let you know either way how it goes, thx again!

Clark

**Comment by nowinski** [comment]
Okay--this is making sense. I'd rather have NULL datetimes in my database than 1901-01-01 0:00:00 and have mostly worked out the code to allow this. CDMS would display blank fields for SQL NULLS. Let me know if you're interested in going this direction. 

Issue documentation:
1. How Excel stores datetimes https://www.myonlinetraininghub.com/excel-date-and-time 
2. Concatenating dates & times in Excel https://www.extendoffice.com/documents/excel/1538-excel-combine-date-and-time.html
3. Moment.JS javascript https://momentjs.com/docs/#/use-it/
4. See cdms frontend code dataset-import.js (line 300ish), dataset_activities-list.js (line 164ish), CDMSTimeCellValidator.js
