### ISSUE TITLE
Metadata not displaying possible values (bug)

### ISSUE THREAD

**Issue by cwatry** [CRITFC/Helpdesk#21]
Metadata is not displaying for fields where the possible values are not a simple JSON array (e.g., ["Value1", "Value2", "Value3", etc]).  For example, a field that references a data source has the possible value array set up like [{"ID":"Value1_ID", "LABEL":"Value1"},{"ID":"Value2_ID", "LABEL":"Value2"}, etc]; however, the possible values in the metadata only displays "[object Object],[object Object],[object Object]," etc.  Needs to be fixed so it displays actual possible values (e.g., [Value1_ID Value1],[Value2_ID Value2],[Value3_ID Value3], etc when using something other than a simple JSON array.

**Comment by kenburcham** [comment]
Not totally sure what you're asking, but in possiblevalues you can do either a simple array or a json array of key+value pairs:
1) ["BUT", "CHF/CO", "STS", "CHS","UNK","PL"]
2) {"D":"Dry", "L":"Low", "M":"Moderate", "H":"High", "F":"Flooding"}

**Comment by nowinski** [comment]
Please post a screenshot

**Comment by nowinski** [comment]
Metadata tab,  Fields, Possible Values not displayed correctly when values come from list table

**Comment by nowinski** [comment]
PS--the same error occurs in the Edit Master Field modal

![Capture2](https://user-images.githubusercontent.com/8331885/74486355-a1244080-4e71-11ea-8592-f0e8f9dd2821.PNG)

I'm adding the same fix to app\core\admin\components\admin-page\templates\modal-edit-master-field.html

![Capture](https://user-images.githubusercontent.com/8331885/74486389-b00af300-4e71-11ea-838c-716ce27e3106.PNG)
