### ISSUE TITLE
Save issue in Edit Project modal Project tab

### ISSUE THREAD

**Issue by cwatry** [CRITFC/Helpdesk#29]
Changes don't save when deleting existing text from fields in the Project tab of the Edit Project modal.  Changes do save successfully when replacing existing text w/ new text; however, if the field is left blank after deleting existing text, the changes do not save.

**Comment by nowinski** [comment]
Confirmed. Was able to reproduce this on my machine. Will look into it.

**Comment by nowinski** [comment]
Traced to nested if logic in modal-edit-project.js:

If the incoming field has a value then
     If the incoming field is multiselect or multiselect-checkbox then
           Do special stuff before getting the value
     Else 
           Just get the value
End

There is no handling for incoming fields without values

![Capture](https://user-images.githubusercontent.com/8331885/93162317-61ecf500-f6c9-11ea-9416-7b4984b63fb6.PNG)

Need to add an Else to the outer If
