### ISSUE TITLE
Feature request: Additional organizational structure/user levels

### ISSUE THREAD

**Issue by cwatry** [CRITFC/Helpdesk#30]
As we expand the use of CDMS to other divisions w/in our department, I see an increasing need to manage CDMS at multiple levels and possibly even partition the site based on program or sub-program.  I can foresee the following levels, to start:

- Admin: across all programs/sub-programs; only granted to a few specific individuals
- Developer: admin privileges for datasets w/in program/sub-program
- User/Editor: read-only access except where assigned as Editor
- others??

**Comment by kenburcham** [comment]
Good idea, Clark. Just by way of documentation, here are the various permission levels CDMS currently supports.

FYI: There is an Organization table and Projects belong to an Organization. Datasets belong to Projects. Datastores are across all organizations. Users belong to an Organization.

For permission levels, currently there are these:


·         Admin – across all organizations/projects/datasets. Can edit all datasets/fields/datastores, etc.

·         User – have read access to all datasets (but could be scoped to just their Organization pretty easily). Some modules have user group restrictions, but those are one-offs.

·         Owner – projects have an OwnerId. If a user owns a project they have write access and can manage editors for datasets in a project. They can’t edit datasets/fields, etc. Only Admins can do that.

·         Editor – has write access to datasets they are an editor for

·         External user – Can login and have read access only to projects (and all project datasets) assigned in their permission. Can be added as an editor by the project Owner.

I like the idea of “Developer” Clark suggested. Could scope by Organization? Or as suggested, by Progam/sub-program

I think we’d implement as groups the user is in and then expand the permission checks for the different features.


------------------------------
Ken Burcham, MDiv
O: 541-429-7444
C: 541-667-7624

**Comment by nowinski** [comment]
Yes--I like the idea of a new permission level between Owner and Admin. We also work with folks from multiple organizations (NPT, YN, WS) so it would be great to offer elevated permissions but only for projects under that organization.
