### ISSUE TITLE
Feature Request: Change visible fields displayed on Project Summary page

### ISSUE THREAD

**Issue by cwatry** [CRITFC/Helpdesk#31]
Is there a place to set the configuration to change the fields displayed on the Project Summary page?  We are able to add new metafields, but how do we get certain one's to display?  Is this something that can be done through the UI or back-end tables or will it require implementing changes to the front-end code?

**Comment by nowinski** [comment]
Yes, new metafields must be manually added to the project summary page. See project-landing.html.

![Capture](https://user-images.githubusercontent.com/8331885/93144981-238f1000-f6a0-11ea-8633-05eb09b5dd5b.PNG)

Pass the MetadataPropertyId (from MetadataValues table) to getMetaField() to pull the correct information from the Db.
