### ISSUE TITLE
CDMS 2.0 Duplicate Checker

### ISSUE THREAD

**Issue by nowinski** [CRITFC/Helpdesk#6]
CDMS 2.0 allows data import for multiple locations; however, the duplicate checker still seems to be set up for CDMS 1.0 style imports (one location per import file). To avoid running a duplicate check on each row of data in the import grid, frontend code tracks which ActivityDates it has processed and only fires the duplicate check query once per ActivityDate. That works fine when there is only one Location per import file. But, when multiple locations are imported, it's possible to have two Activities with the same date. And since the duplicate check query only fires once per date, some duplicate activities can slip through the test. 

See modal-activities-grid.js

**Comment by roec-critfc** [comment]
Okay, I’ll get into this starting next week.  Still messing with git at the moment.

**Comment by nowinski** [comment]
This issue was discussed during the September CDMS Management call. A patch has been committed to cdms-fe-public repository. 

See commit here: [https://github.com/CRITFC/cdms-fe-public/commit/9bd2d5bac71f97965a5be6761238fb301de6b2f0](url)

Closing this issue for now.
