### ISSUE TITLE
Set up a 2.5* Dev Environment with CRITFC-renamed to 3.0

### ISSUE THREAD

**Issue by dspinosa** [CRITFC/Helpdesk#69]
This will allow the CRITFC team to test the latest release of CDMS (2.5) from CTUIR.  Although there are conflicts in the merge file, many are related to the Angular update on the frontend, and NuGet and .Net packages in the backend.

**Comment by dspinosa** [comment]
Need Server for FE, BE, and database

**Comment by JamminCRITFC** [comment]
VM dev server is up and currently running old 2.3 version. Ready to install v3.

**Comment by sekoukeita** [comment]
Innovate local dev environments are ready and working on discovering database changes and fixing bugs and errors preventing the front and backend to communicate seamlessly with the database provided by NPT

**Comment by sekoukeita** [comment]
We have worked on comparing schemas of CDMS database vs NPT database (provided by Clark)
to make our development environment work.

# Database comparison 

## Overall differences
- tables, views and users have been added to the NPT database 
- tables, views and users have been deleted from the NPT database 
- changes in tables and view (add, deletion of columns) 

## Changes to core tables and views: 

### Users:  
- missing Cell column 
- added WorkPhone and PhoneExtension columns 

### Datasets: 
- added ArchiveDatasetId 

###  Locations: 
- missing Quadrangel and RelatedHabProject columns 
- added LocationTypeId 

###  LocationDatasets:  
- this table was missing in NPT database 

### LocationProjects: 
- this table was added to the NPT database 

### Datastores: 
- added LocationTypeId 

### DatasetFields: 
- missing PossibleValues and Disabled columns 

###  ProjectObjectives: 
- this table was missing in the NPT database 

###  Projects_VW (view): 
- missing LocationId, SdeObjectId, SdeFeatureClassId columns 
- missing Project-LocationProject-Location join 

# Update the database to make the dev environment work 

1. Added Cell column to Users table to make the Login work 
2. Deleted LocationTypeId from DataStores and LocationsTable 
3. Created LocationDatasets junction table and populate it 
4. Created ProjectObjectives table 
5.  Added PossibleValues and Disabled columns to DatasetFields tabled 
6. Added Quadrangle and RelateHabProject columns to Locations table 
7. Added the dataset with id = 1262 to the Datasets table. Note: this dataset is 	always called in Location tab. 
8.  Wrote a SQL script to automate the above 7 steps.

**Comment by cwatry** [comment]
Sekou et al. -

I think we will want to retain the LocationTypeId field in dbo.Locations as this will help us when we consolidate our location records to remove duplicates and re-assign the correct LocationId in its place.  I think this will be a necessary step for each tribe to take to remove any existing duplicate locations.  For example, we created transects for our raw field data from spawning ground surveys (i.e., location type = Spawning Ground Survey) and we use those same transects in summarized datasets (e.g., location type = Ageing Data).  Currently in dbo.Locations we have two location records w/ separate LocationId's to represent this one location.  So it's that kind of thing we need to clean up on a case-by-case basis; I think using LocationTypeId will make this task much easier.  Thanks

Clark

**Comment by sekoukeita** [comment]
# Installing tribalCDMS_3.0 on dev environment
1- Clone the [front](https://github.com/CRITFC/tribalCDMS-fe/tree/tribalCDMS_3.0) and [backend ](https://github.com/CRITFC/tribalCDMS-be/tree/tribalCDMS_3.0)repositories from CRITFC GitHub onto the dev machine.

2- Get the backend ready (in Visual Studio)
- add the [Web.config](https://drive.google.com/file/d/1LOfGjupdFXRga5x4SDpBIwjC4K5UPke8/view?usp=sharing) file to the service folder.
- update the Web.config entries like the database connection string, the masquerade password and other relevant entries.

3- Publish the backend (in Visual Studio)
- publish the services project, targeting the services folder physical path defined in IIS to receive services built application

4- Get the frontend ready (in Visual Studio Code)
- add the [config.ts](https://drive.google.com/file/d/1aEYFE1_F0quhlCXWliCGYYcGbnRiyxuL/view?usp=sharing) to src/appjsLegacy.
- update the config.ts file:
. change the serverUrl and serviceUrl to match your IIS environment
. change other relevant entries to match your IIS environment
- in the terminal, run `npm install` to install the node_modules
- check your Node, Angular Core and Angular CLI version by running `ng version` in the terminal
- it is better to have the following version (or close to them):
. Node: 16.15.0
. Angular Core: 11.2.14
. Angular CLI: 11.2.14
- Make sure the project compiles with no error by running `ng serve`
- Build the project, targeting cdms-fe folder physical path location in IIS defined to receive the frontend application.
. for example if that location absolute path is `C:\MySite\cdms-fe`
. make sure the folder exists and is empty
. run `ng build --output-path C:\MySite\cdms-fe`

5- In IIS:
. restart the server
.recycle and restart the application pool for the site
.restart the site.

**Comment by JamminCRITFC** [comment]
Development environments have been setup at CRITFC and NPT.
