### ISSUE TITLE
Add new datasets and build new datastores via web portal

### ISSUE THREAD

**Issue by JamminCRITFC** [CRITFC/Helpdesk#74]
Current CRITFC v2.3 requires programming in Visual Studio when creating and modifying datasets. A much-needed feature is for users to import new datasets and build datastores using the web interface.

**Comment by ryankinzer** [comment]
The v2.3 that we are running in prod allows for dataset creation through the UI and doesn't require programming. Versions earlier than v2.3 did require programming/database migrations to create new datasets.
