### ISSUE TITLE
Change Text from Dataset to Datastore in web interface of CDMS

### ISSUE THREAD

**Issue by keld1280** [CRITFC/Helpdesk#9]
I am wondering if, where appropriate, the Text/Titles on webpages in CDMS can be changed to Datastore(s) instead of Dataset(s)?  As a user who is familiar with CDMS, it is confusing for me to understand at what level I am working when clicking through webpages of material to edit.  Thanks.

**Comment by nowinski** [comment]
Yes, I think on the administrative page we can change Dataset and Master Dataset to Datastore. Please submit screen shots of any other pages where this may be confusing. Thanks. 

![Capture](https://user-images.githubusercontent.com/8331885/66077629-2dfadd00-e515-11e9-877c-1774b8dada4f.PNG)

**Comment by keld1280** [comment]
Identifying what pages and titles are datastore vs datasets, when only the text "dataset" is used is what is confusing.  I will work on it and see if I can figure it out.


Denise

________________________________
